name: Dev builds

on:
  push:
    branches:
      - arm_testing

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Build kubernetes-fluentd
        run: make build && docker image ls
      - name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: odidev
          password: nibble@123

      - name: Login to AWS public ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PUBLIC_ECR_SECRET_ACCESS_KEY }}
      - name: Push kubernetes-fluentd
        run: make push
