name: Dev builds

on:
  push:
    branches:
      - arm_testing

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build kubernetes-fluentd
        run: make build
      - name: Build kubernetes-fluentd
        run: make build-arm64
      - name: Login to AWS public ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PUBLIC_ECR_SECRET_ACCESS_KEY }}
      - name: Push kubernetes-fluentd
        run: make push
